import { compile } from "../src/compile.js"

const r = await compile([
    "-- `...` is still Lua's pack.",
    "function firstTwo(...: number)",
    "    const a, b = ...",
    "    return a, b",
    "end",
    "",
    "-- `...rest` is JavaScript's rest parameter: an array.",
    "function join(sep: string, ...parts: string[]): string",
    "    return table.concat(parts, sep)",
    "end",
    "",
    "function count(...items: number[]): number",
    "    let total = 0",
    "    for _, n in items do",
    "        total += n",
    "    end",
    "    return total",
    "end",
    "",
    "class Logger",
    "    prefix: string",
    "    constructor(prefix: string)",
    "        this.prefix = prefix",
    "    end",
    "    function say(...words: string[]): string",
    "        return this.prefix .. table.concat(words, \" \")",
    "    end",
    "end",
    "",
    "print(firstTwo(1, 2, 3))",
    `print(join("-", "a", "b", "c"))`,
    "print(count(1, 2, 3, 4))",
    `print(new Logger("> "):say("hello", "there"))`,
].join("\n"))
for (const d of r.diagnostics) console.log(`! ${d.line}:${d.column} ${d.message}`)
console.log(r.code)
